Esthetik_Lavoie/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/reglages', [App\Http\Controllers\ReglagesController::class, 'index'])->name('reglages')->middleware('admin');
Route::get('/articles', [App\Http\Controllers\ArticlePageController::class, 'index'])->name('articles');
Route::get('/services', [App\Http\Controllers\ServicePageController::class, 'index'])->name('services');
Route::get('/communication', [App\Http\Controllers\CommunicationPageController::class, 'index'])->name('communication');
Route::get('/panier', [App\Http\Controllers\PanierController::class, 'index'])->name('panier')->middleware('auth');
Route::get('/ajout-article/{article}', [App\Http\Controllers\PanierController::class, 'ajouterArticle'])->name('panier.ajouterArticle')->middleware('auth');
Route::get('/ajout-service/{service}', [App\Http\Controllers\PanierController::class, 'ajouterService'])->name('panier.ajouterService')->middleware('auth');
Route::get('/panier/supprimer/{itemId}', [App\Http\Controllers\PanierController::class, 'destroy'])->name('panier.destroy')->middleware('auth');

Route::resource('article', 'App\Http\Controllers\ArticleController')->middleware('admin');
Route::resource('service', 'App\Http\Controllers\ServiceController')->middleware('admin');
Route::resource('notification', 'App\Http\Controllers\NotificationController')->middleware('admin');
Route::resource('historiqueVentes', 'App\Http\Controllers\HistoriqueVentesController')->middleware('admin');
Route::resource('vehicule', 'App\Http\Controllers\VehiculeController')->middleware('admin');

Esthetik_Lavoie/app/Http/Controllers/ServicePageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Service;
use App\Models\ServiceVehicule;
use Illuminate\Http\Request;

class ServicePageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $services = Service::all();
        return view('servicePage.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

Esthetik_Lavoie/resources/views/servicePage/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron" style="padding-top: 15px">
                <div class="d-flex justify-content-between">
                    <h1>Services</h1>
                    <div class="dropdown">
                        <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sélectionner type de Véhicule
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">Automobile</a>
                            <a class="dropdown-item" href="#">Camion</a>
                            <a class="dropdown-item" href="#">VUS</a>
                        </div>
                    </div>
                    @auth
                        @if (Auth::user()->role==1)
                            <a href="{{ route('service.create') }}" class="btn btn-primary text-justify">Ajouter un service</a>
                        @endif
                    @endauth
                </div>
                @foreach($services as $service)
                    <div class="card mt-3">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4 class="card-title">{{ $service->nom }}</h4>
                                <h3>{{ $service->prix }}$</h3>
                            </div>
                            <p class="card-text">{{ $service->description }}</p>
                            @auth
                                <div class="text-right">
                                    @if (Auth::user()->role == 1)
                                        <a href="{{ route('service.edit', [$service->id]) }}" class="card-link pr-3">Modifier</a>
                                    @endif
                                        <a href="{{ route('panier.ajouterService', [$service->id]) }}" class="btn btn-dark">Ajouter au panier</a>
                                </div>
                            @endauth
                        </div>
                    </div>
                @endforeach
            </div>
        </section>
    </div>

@stop