Esthetik_Lavoie/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/home');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/reglages', [App\Http\Controllers\ReglagesController::class, 'index'])->name('reglages')->middleware('admin');
Route::get('/articles', [App\Http\Controllers\ArticlePageController::class, 'index'])->name('articles');
Route::get('/services', [App\Http\Controllers\ServicePageController::class, 'index'])->name('services');
Route::get('/communication', [App\Http\Controllers\CommunicationPageController::class, 'index'])->name('communication');
Route::get('/panier', [App\Http\Controllers\PanierController::class, 'index'])->name('panier')->middleware('auth');
Route::get('/ajout-article/{article}', [App\Http\Controllers\PanierController::class, 'ajouterArticle'])->name('panier.ajouterArticle')->middleware('auth');
Route::get('/ajout-service/{service}', [App\Http\Controllers\PanierController::class, 'ajouterService'])->name('panier.ajouterService')->middleware('auth');
Route::get('/panier/supprimer/{itemId}', [App\Http\Controllers\PanierController::class, 'destroy'])->name('panier.destroy')->middleware('auth');

Route::resource('article', 'App\Http\Controllers\ArticleController')->middleware('admin');
Route::resource('service', 'App\Http\Controllers\ServiceController')->middleware('admin');
Route::resource('notification', 'App\Http\Controllers\NotificationController')->middleware('admin');
Route::resource('historiqueVentes', 'App\Http\Controllers\HistoriqueVentesController')->middleware('admin');
Route::resource('vehicule', 'App\Http\Controllers\VehiculeController')->middleware('admin');

Esthetik_Lavoie/app/Http/Controllers/ArticlePageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Article;
use Illuminate\Http\Request;

class ArticlePageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('articlePage.index', compact('articles'));
    }
}

Esthetik_Lavoie/resources/views/articlePage/index.blade.php
@extends('layouts.app')
@section('content')

    <div class="container">
        <section class="section-padding">
            <div class="jumbotron" style="padding-top: 15px">
                <div class="d-flex justify-content-between">
                    <h1>Articles</h1>
                    @auth
                        @if (Auth::user()->role==1)
                            <a href="{{ route('article.create') }}" class="btn btn-primary text-justify">Ajouter un article</a>
                        @endif
                    @endauth
                </div>
                @foreach($articles as $article)
                    <div class="card mt-3">
                        <div class="card-body">
                            <div class="d-flex justify-content-between">
                                <h4 class="card-title">{{ $article->nom }}</h4>
                                <h3>{{ $article->prix }}$</h3>
                            </div>
                            <p class="card-text">{{ $article->description }}</p>
                            @auth
                                <div class="text-right">
                                    @if (Auth::user()->role == 1)
                                        <a href="{{ route('article.edit', [$article->id]) }}" class="card-link pr-3">Modifier</a>
                                    @endif
                                    @if ($article->quantite_disponible > 0)
                                        <a href="{{ route('panier.ajouterArticle', [$article->id]) }}" class="btn btn-dark">Ajouter au panier</a>
                                    @else
                                        <a href="#" class="btn btn-dark disabled">Ajouter au panier</a>
                                        <label class="d-flex justify-content-end" style="margin-bottom: -15px">En rupture de stock...</label>
                                    @endif
                                </div>
                            @endauth
                        </div>
                    </div>
                @endforeach
            </div>
        </section>
    </div>

@stop